[ejs.landing]
updateAvailableTooltip = "Mise à jour Disponible"
usernamePlaceholder = "PSEUDO"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS-LIGNE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun Serveur Sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Rafraichissement des Actualités..."
newsErrorFailedSpan = "Échec du Chargement des Actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune Actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* valeur invalide"
loginEmailPlaceholder = "EMAIL OU PSEUDO"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de Passe Oublié ?"
loginRememberMeText = "Se Souvenir de Moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un Compte ?"
loginPasswordDisclaimer1 = "Vos informations de connexion sont directement envoyées de manières cryptées à Mojang et Microsoft."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de Connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs Disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un Compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À Propos"
navUpdates = "Mises à Jour"
navDone = "Sauvegarder"
tabAccountHeaderText = "Paramètres de Compte"
tabAccountHeaderDesc = "Ajouter un Compte ou en Gérer un Existant."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un Compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un Compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options relatives au lancement du jeu."
gameResolutionTitle = "Résolution du Jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur lors du lancement."
launchDetachedTitle = "Lancer le jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n'est pas lancer séparément du launcher, la fermeture de ce dernier fermera le jeu."
tabModsHeaderText = "Paramètres de Mods"
tabModsHeaderDesc = "Activer et gérer les mods."
switchServerButton = "Changer"
requiredMods = "Mods Requis"
optionalMods = "Mods Optionnels"
dropinMods = "Drop-in Mods"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour rafraichir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Enable or disable shaders. Please note, shaders will only run smoothly on powerful setups. You may add custom packs here."
selectShaderpack = "Select Shaderpack"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer les configurations Java (pour utilisateurs avancés)."
memoryTitle = "Mémoire RAM"
maxRAM = "RAM Maximale"
minRAM = "RAM Minimale"
memoryDesc = "EarthKingdoms nécessite un minimum de 4Go de RAM pour jouer dans de bonnes conditions."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner un Exécutable Java"
javaExecSelButtonText = "Choisir un Fichier"
javaExecDesc = "L'exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin d'accès doit finir avec <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM Aditionnelles"
jvmOptsDesc = "Options à fournir à la JVM au moment de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne devrait pas être inclus."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options relatives au launcher lui-même."
allowPrereleaseTitle = "Allow Pre-Release Updates."
allowPrereleaseDesc = "Pre-Releases include new features which may have not been fully tested or integrated.<br>This will always be true if you are using a pre-release version."
dataDirectoryTitle = "Dossier de Jeu"
selectDataDirectory = "Sélectionner un Dossier de Jeu"
chooseFolder = "Choisir un Dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et installations Java seront stockés dans ce dossier ci-dessus.<br>Les screenshots et les schematics seront stockés dans le dossier 'instance', puis 'ekserver-1.12.2'."
aboutTabHeaderText = "À Propos"
aboutTabHeaderDesc = "Regarder les informations de mise à jour de la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version Stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Notes de Mise à Jour :"
changelog = "Changelog"
noReleaseNotes = "Aucune Notes de Mise à Jour"
viewReleaseNotes = "Voir les Notes de Mise à Jour sur GitHub"
launcherUpdatesHeaderText = "Mises à Jour du Launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer, et revoir les mises à jour du launcher."
checkForUpdates = "Recherche de Mise à Jour"
whatsNew = "Quoi de Nouveau ?"
updateReleaseNotes = "Notes de Mise à Jour"

[ejs.waiting]
waitingText = "En Attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En Attente du Client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "SE CONNECTER"
success = "CONNEXION RÉUSSIE"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur Invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur Inconnue Durant le Lancement"
desc = "Une erreur inconnue à été constatée lors du lancement du jeu. Merci de regarder la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur Durant le Lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun Compte Sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun Serveur Sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS-LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos de système..."
noCompatibleJava = "Aucune Installation Java<br>Compatible Trouvée"
installJavaMessage = "Pour pouvoir lancer Minecraft, il vous faut une installation 64-bit de Java {major}. Voulez-vous installer une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer Manuellement"
javaDownloadPrepare = "Préparation à l'Installation de Java..."
javaDownloadFailureTitle = "Erreur Durant le Téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est Requis<br>pour le Lancement"
javaRequiredMessage = 'Une installation x64 compatible de Java {major} est requis pour le lancement.<br>Veuillez en installer une.'
javaRequiredDismiss = "OK"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution OpenJDK."
javaDownloadCorruptedError = "L'exécutable JDK téléchargé a un mauvais hachage, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java Installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos du serveur..."
fatalError = "Erreur Fatale"
unableToLoadDistributionIndex = "Chargement de la distribution du launcher impossible. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur Durant le Lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation des fichiers d'intégrités..."
errorDuringFileVerificationTitle = "Erreur Durant la Vérification des Fichiers"
downloadingFiles = "Téléchargements des Fichiers..."
errorDuringFileDownloadTitle = "Erreur Durant le Téléchargement des Fichiers"
preparingToLaunch = "Préparation au Lancement..."
launchingGame = "Lancement du Jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, ne s'est pas téléchargé correctement. Dans ce cas-là, le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactiver temporairement votre Anti-Virus et lancer votre jeu."
doneEnjoyServer = "Jeu Lancé"
checkConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Rafraichissement des Actualités"

[js.landing.discord]
loading = "Chargement du Jeu..."
joining = "Sailing to Westeros!"
joined = "Exploring the Realm!"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les Fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelques Chose S'est Mal Passée..."
errorMessage = "Échec de l'Authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelques Chose S'est Mal Passée..."
errorMessage = "Échec de la Déconnexion Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un Compte"
selectedButton = "Compte Sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est Votre Dernier Compte Connecté"
lastAccountWarningMessage = "Pour utiliser le launcher, il doit y avoir au moins un compte connecté. Vous devrez vous réconnectez après.<br><br>Vous êtes sûr de vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Pseudo"
uuid = "UUID"
selectAccount = "Sélectionner un Compte"
selectedAccount = "Compte Sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Remove"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Serveur Principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection Invalide"
requiresJava = "Requis Java {major} x64."
availableOptions = "Options Disponible pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version Stable"
releaseNotesFailed = "Échec du Chargement des Notes de Mise à Jour."

[js.settings.updates]
newReleaseTitle = "Nouvelle Version Disponible"
newPreReleaseTitle = "Nouvelle Pré-version Disponible"
downloadingButton = "Téléchargement en Cours.."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermer le launcher et exécuter le .dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous avez la Dernière Version"
checkForUpdatesButton = "Recherche de Mise à Jour"
checkingForUpdatesButton = "Recherche de Mise à Jour en Cours..."

[js.uibinder.startup]
fatalErrorTitle = "Erreur Fatale : Impossible de Charger l'Index de Distribution"
fatalErrorMessage = "Une connexion n'a pas pu être établie avec nos serveurs pour télécharger l'index de distribution. Aucune copie locale n'était disponible pour le chargement. <br><br>L'index de distribution est un fichier essentiel qui fournit les dernières informations sur le serveur. Le launcher ne peut pas démarrer sans ce fichier. Assurez-vous d'être connecté à Internet et relancez le launcher."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec du Rafraichissement de la Connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous connecter à nouveau."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez réessayer."
loginButton = "Connexion"
selectAnotherAccountButton = "Sélectionner un Autre Compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de Mise à Jour en Cours..."
installNowButton = "Installer la Mise à Jour"
checkForUpdatesButton = "Recherche de Mise à Jour"